import {
  ApplicationConfig,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
  provideZoneChangeDetection,
} from '@angular/core';
import { provideRouter, withInMemoryScrolling } from '@angular/router';

import { routes } from './app.routes';
import { provideClientHydration, withEventReplay } from '@angular/platform-browser';
import { provideHttpClient, withFetch, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './core/interceptors/auth-interceptor';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
// import { provideIonicAngular } from '@ionic/angular';

import {
  LucideAngularModule,
  Sun,
  Moon,
  Menu,
  X,
  Trash2,
  Mail,
  MapPin,
  LogOut,
  Link2,
  ArrowLeft,
  Bell,
  CheckCheck,
  ExternalLink,
  Github,
  Linkedin,
  Facebook,
  Instagram,
  Twitter,
  ArrowRight,
  ChevronsRight,
  SquarePen,
  MoveRight,
  Phone,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Search,
  ListFilter,
  Briefcase,
  GraduationCap,
  BriefcaseBusiness,
  Check,
  MonitorSmartphone,
  Server,
  LayoutDashboard,
  Eye,
  EyeOff,
  Users,
  ClipboardList,
  Plus,
  Sparkles,
  Clock,
  ArrowUpRight,
  MessageSquare,
  FolderKanban,
  Layers,
  FileText,
  RotateCw,
  TriangleAlert,
  Download,
  SlidersHorizontal,
  Calendar,
  ImagePlus,
  Image,
  Maximize2,
  User,
  Inbox,
  Send,
  ShieldCheck,
  Copy,
  Globe,
  ArrowUp,
  ArrowDown,
  ArrowUpDown,
  Heart,
  CornerDownRight,
} from 'lucide-angular';
export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(
      routes,
      withInMemoryScrolling({
        scrollPositionRestoration: 'top',
        anchorScrolling: 'enabled',
      }),
    ),
    provideClientHydration(withEventReplay()),
    provideAnimationsAsync(),

    // provideIonicAngular(),

    provideHttpClient(withInterceptors([authInterceptor])),

    importProvidersFrom(
      LucideAngularModule.pick({
        Sun,
        Moon,
        Bell,
        CheckCheck,
        Menu,
        Eye,
        EyeOff,
        X,
        Trash2,
        Mail,
        Phone,
        MapPin,
        LogOut,
        Link2,
        SquarePen,
        ArrowLeft,
        ArrowRight,
        MoveRight,
        Check,
        ChevronLeft,
        ChevronRight,
        ChevronsRight,
        ChevronDown,
        ChevronUp,
        Search,
        ListFilter,
        ExternalLink,
        Briefcase,
        GraduationCap,
        BriefcaseBusiness,
        Github,
        Linkedin,
        Facebook,
        Instagram,
        Twitter,
        MonitorSmartphone,
        Server,
        LayoutDashboard,
        Users,
        ClipboardList,
        Plus,
        Sparkles,
        Clock,
        ArrowUpRight,
        MessageSquare,
        FolderKanban,
        Layers,
        FileText,
        RotateCw,
        TriangleAlert,
        Download,
        SlidersHorizontal,
        Calendar,
        ImagePlus,
        Image,
        Maximize2,
        User,
        Inbox,
        Send,
        ShieldCheck,
        Copy,
        Globe,
        ArrowUp,
        ArrowDown,
        ArrowUpDown,
        Heart,
        CornerDownRight,
      }),
    ),
  ],
};
